"""B3 candidate grid and selection rules for AirSense V2.

Protocol Phase 3. **Frozen before validation was opened**, and not changed
afterwards.

Exactly eight candidates, generated by a documented nested loop:

    for learning_rate in [0.03, 0.07]:
        for num_leaves in [31, 63]:
            for min_child_samples in [50, 200]:

giving B3_C01 ... B3_C08 in that order. Everything else is fixed, including
``n_estimators = 400`` with **no early stopping** - an early-stopped iteration
count would be one more quantity selected by looking at validation.
"""

from collections import OrderedDict

LEARNING_RATES = [0.03, 0.07]
NUM_LEAVES = [31, 63]
MIN_CHILD_SAMPLES = [50, 200]

N_ESTIMATORS = 400

# Native LightGBM parameter spelling, as the protocol requires: the installed
# lightgbm 4.7.0 sklearn wrapper needs scikit-learn, which is not part of the
# frozen V2 runtime, so training uses the native Booster API. The scientific
# grid is unchanged - only the spelling is native. Every randomness source is
# pinned and every subsampling fraction is 1.0, so no stochastic behaviour
# remains.
FIXED = OrderedDict([
    ("objective", "regression_l1"),
    ("metric", "l1"),
    ("max_depth", -1),
    ("bagging_fraction", 1.0),
    ("bagging_freq", 0),
    ("feature_fraction", 1.0),
    ("lambda_l1", 0.0),
    ("lambda_l2", 1.0),
    ("seed", 42),
    ("data_random_seed", 42),
    ("feature_fraction_seed", 42),
    ("bagging_seed", 42),
    ("extra_seed", 42),
    ("deterministic", True),
    ("force_col_wise", True),
    ("verbosity", -1),
])

SKLEARN_EQUIVALENT = OrderedDict([
    ("n_estimators", "num_boost_round (passed to lgb.train)"),
    ("min_child_samples", "min_data_in_leaf"),
    ("subsample", "bagging_fraction"),
    ("subsample_freq", "bagging_freq"),
    ("colsample_bytree", "feature_fraction"),
    ("reg_alpha", "lambda_l1"),
    ("reg_lambda", "lambda_l2"),
    ("random_state", "seed"),
    ("n_jobs", "num_threads"),
    ("verbose", "verbosity"),
])

SELECTION_CRITERION = "macro_station_validation_mae"
TIE_BREAK_ORDER = [
    "lower macro-station MAE",
    "lower macro-station RMSE",
    "smaller num_leaves",
    "larger min_child_samples",
    "lower candidate id",
]
COMPARISON_TOLERANCE = 1e-12
REGIMES = ["R0", "R1", "R2"]
HORIZONS = [1, 6, 12, 24]


def candidates(n_jobs):
    """The eight frozen candidates, in frozen order."""
    grid = []
    index = 0
    for learning_rate in LEARNING_RATES:
        for num_leaves in NUM_LEAVES:
            for min_child_samples in MIN_CHILD_SAMPLES:
                index += 1
                parameters = OrderedDict(FIXED)
                parameters["learning_rate"] = learning_rate
                parameters["num_leaves"] = num_leaves
                parameters["min_data_in_leaf"] = min_child_samples
                parameters["num_threads"] = n_jobs
                grid.append(OrderedDict([
                    ("candidate_id", "B3_C%02d" % index),
                    ("learning_rate", learning_rate),
                    ("num_leaves", num_leaves),
                    ("min_child_samples", min_child_samples),
                    ("parameters", parameters),
                    ("num_boost_round", N_ESTIMATORS),
                ]))
    return grid


def select(results):
    """Apply the frozen selection criterion and tie-break order.

    `results` is an iterable of dicts carrying candidate_id, num_leaves,
    min_child_samples, macro_station_mae and macro_station_rmse.
    """
    def key(row):
        return (round(row["macro_station_mae"] / COMPARISON_TOLERANCE),
                round(row["macro_station_rmse"] / COMPARISON_TOLERANCE),
                row["num_leaves"],
                -row["min_child_samples"],
                row["candidate_id"])
    return sorted(results, key=key)[0]
